server:
  port:8080
  
zuul:
  host:
    socket-timeout-millis: 10000
  routes:
    book-service:
      path: /books/**
      name: book-service ## use name
      stripPrefix: false
      sensitiveHeaders:
    book-service-test: ## Just annother test configuration. So http://localhost:8080/bs/books will work the same way as http://localhost:8080/books
      path: /bs/**
      serviceId: book-service  ## use serviceId
      stripPrefix: true ## http://localhost:8080/bs/books  bs will be tripped when proxy to book-service
      sensitiveHeaders:
    bookmarks:
      path: /bookmarks/**
      serviceId: bookmark-service
      stripPrefix: true
      sensitiveHeaders: 
### Eureka configuration ######################## 
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/